version: '3'
services:
  consul:
    image: "consul:1.15.4"
    ports:
      - "8500:8500"
  mysql:
    image: 'mysql:8.0.40-debian'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=user
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379